### ISSUE TITLE
7) Pratica de banco de dados

### ISSUE THREAD

**Issue by rabispedro** [rabispedro/thunder-hawks-arpia#11]
Modelar e criar o banco relacional , para conter as seguintes informaçoes:
1) Aluno ( matricula,nome,nomepai,nomemae,dtnascimento,dtmatricula,turma,sexo)
2) Turma(turno, serie ,nometurma,professor)
3) Professor (nomeProfessor,dtnascimento,especialidade)
4) Especialidade(nomeEspecialidade)

[INSERTS]
Incluir 200 alunos distribuidos em 3 turmas, sendo 100 alunos homens e 100 mulheres
Incluir 10 turmas
Incluir 10 professores ( 1 professor por turma )
Incluir 5 especialidades de professores ( 1 professor pode ter N especialidades)

[SELECTS]
Relatorios: 
1) Retornar todos alunos ordenados por turmas , por nome em ordem alfabetica
2) Retornar as turmas em que não existem alunos
3) Retornar as especialidades dos professores que possuem turmas
4) Retornar a idade média dos professores que possuem turma
5) Retornar a quantidade de alunos de cada sexo por turma

**Comment by rabispedro** [comment]
Link para visualização do Banco de Dados (Draw.io): https://drive.google.com/file/d/1Zgsr1lVGU4HCKsfMz__Qh7T8SuMC4L2C/view?usp=sharing

**Comment by rabispedro** [comment]
Link para visualização do Banco de Dados (Draw.io): https://drive.google.com/file/d/1Zgsr1lVGU4HCKsfMz__Qh7T8SuMC4L2C/view?usp=sharing

**Comment by rabispedro** [comment]
Estou modelando o banco (utilizando UUID para chaves do tipo pk_id) e pesquisando sobre gerar dados aleatórios dentro do SQL.

**Comment by rabispedro** [comment]
Adicionado ao mock os INSERTS de Especialidade, Professor e Turma.

**Comment by rabispedro** [comment]
Modelagem e Inserções quase completamente devidamente finalizadas.

Observação: falta implementar a relação OneToMany de tb_professor para tb_especialidade.

**Comment by rabispedro** [comment]
Query 1, 2 e 3 implementadas.

**Comment by joaolima-code** [comment]
Aviso: A finalização da atividade tem que ser feita hoje. Lembrando que as 3 primeiras query já foram feitas (se não me engano a query um apresenta um defeito) e necessita realizar outro laço de relação.
