### ISSUE TITLE
8) Explicar conceitos sobre JSON e XML

### ISSUE THREAD

**Issue by rabispedro** [rabispedro/thunder-hawks-arpia#12]

**Comment by joaolima-code** [comment]
Finalização Apresentação (Slides), já vou encaminhar para o grupo validar

**Comment by joaolima-code** [comment]
Por favor Validem: https://docs.google.com/presentation/d/17P6SWEnIxvmWHCc8C51x8IE34GKAVomDjbqi7hbTCXw/edit?usp=sharing

Vou encaminhar Discord também.

**Comment by FernandoSimoes7** [comment]
@joaolima-code Ficou de desenvolver o trabalho no Google apresentações e eu comecei as pesquisar para a elaboração da apresentação prática.
