### ISSUE TITLE
9) Explicação e demonstração sobre docker

### ISSUE THREAD

**Issue by rabispedro** [rabispedro/thunder-hawks-arpia#13]
Apresentar qual o problema que essa tecnlogia resolve.
Apresentar os principais conceitos dos componentes como: Docker Daemon/Docker Client/Docker Image/Docker Container /Docker Engine/Docker Registry/Docker Hub/Dockerfile/Docker Compose/Docker Swarm
Apresentar a execução do container com a imagem Hello World

**Comment by CarlitoAlves** [comment]
Vou tratar da apresentação e o Pedro da execução.

**Comment by CarlitoAlves** [comment]
Apresentação finalizada e docker instalado falta configuração final
