### ISSUE TITLE
5) Conceitos teoricos e diferenças entre sobre API REST e SOAP

### ISSUE THREAD

**Issue by rabispedro** [rabispedro/thunder-hawks-arpia#9]
Farei a API REST.

Referencia: https://blog.geekhunter.com.br/sua-api-nao-e-restful-entenda-por-que/

**Comment by rabispedro** [comment]
Link do trabalho (Google Apresentação): https://docs.google.com/presentation/d/1aUUxYZEqznzOb334nSlfLHSJqH4UscfE_idzy_kqatQ/edit?usp=sharing

**Comment by joaolima-code** [comment]
Organizei e fiz melhorias estéticas  na apresentações
